version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - APP_ENV=development
      - APP_VERSION=0.1.0
    volumes:
      - ./:/app:rw
